config/routes.rb
Rails.application.routes.draw do
  resources :rental_item_images
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :rental_items

  root 'rental_items#index'

end

app/models/rental_item.rb
class RentalItem < ActiveRecord::Base
  has_many :rental_item_images
  accepts_nested_attributes_for :rental_item_images
  validates :price, numericality:{greater_than:0}
  validates :description, length:{ in: 5..100 }
end

app/models/rental_item_image.rb
class RentalItemImage < ActiveRecord::Base
  mount_uploader :item_image, RentalItemImageUploader
  belongs_to :rental_item
  validates :rental_item_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    redirect_to :root
  end
end

app/controllers/rental_item_images_controller.rb
class RentalItemImagesController < ApplicationController
  before_action :set_rental_item_image, only: [:show, :edit, :update, :destroy]

  # GET /rental_item_images
  # GET /rental_item_images.json
  def index
    @rental_item_images = RentalItemImage.all
  end

  # GET /rental_item_images/1
  # GET /rental_item_images/1.json
  def show
  end

  # GET /rental_item_images/new
  def new
    @rental_item_image = RentalItemImage.new
  end

  # GET /rental_item_images/1/edit
  def edit
  end

  # POST /rental_item_images
  # POST /rental_item_images.json
  def create
    @rental_item_image = RentalItemImage.new(rental_item_image_params)

    respond_to do |format|
      if @rental_item_image.save
        format.html { redirect_to @rental_item_image, notice: 'Rental item image was successfully created.' }
        format.json { render :show, status: :created, location: @rental_item_image }
      else
        format.html { render :new }
        format.json { render json: @rental_item_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_item_images/1
  # PATCH/PUT /rental_item_images/1.json
  def update
    respond_to do |format|
      if @rental_item_image.update(rental_item_image_params)
        format.html { redirect_to @rental_item_image, notice: 'Rental item image was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental_item_image }
      else
        format.html { render :edit }
        format.json { render json: @rental_item_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_item_images/1
  # DELETE /rental_item_images/1.json
  def destroy
    @rental_item_image.destroy
    respond_to do |format|
      format.html { redirect_to rental_item_images_url, notice: 'Rental item image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_item_image
      @rental_item_image = RentalItemImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_item_image_params
      params.require(:rental_item_image).permit(:rental_item_id, :item_image, :contains_items_not_included)
    end
end

app/controllers/rental_items_controller.rb
class RentalItemsController < ApplicationController
  before_action :set_rental_item, only: [:show, :edit, :update, :destroy]

  # GET /rental_items
  # GET /rental_items.json
  def index
    @rental_items = RentalItem.all
  end

  # GET /rental_items/1
  # GET /rental_items/1.json
  def show
      @rental_item_images = @rental_item.rental_item_images.all
  end

  # GET /rental_items/new
  def new
    @rental_item = RentalItem.new
    @rental_item_image = @rental_item.rental_item_images.build
  end

  # GET /rental_items/1/edit
  def edit
  end

  # POST /rental_items
  # POST /rental_items.json
  def create
    @rental_item = RentalItem.new(rental_item_params)

    respond_to do |format|
      if @rental_item.save
        params[:rental_item_images]['item_image'].each do |a|
          @rental_item.rental_item_images.create!(:item_image => a)
        end
        format.html { redirect_to @rental_item, notice: 'Rental item was successfully created.' }
        format.json { render :show, status: :created, location: @rental_item }
      else
        format.html { render :new }
        format.json { render json: @rental_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_items/1
  # PATCH/PUT /rental_items/1.json
  def update
    respond_to do |format|
      if @rental_item.update(rental_item_params)
        format.html { redirect_to @rental_item, notice: 'Rental item was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental_item }
      else
        format.html { render :edit }
        format.json { render json: @rental_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_items/1
  # DELETE /rental_items/1.json
  def destroy
    @rental_item.destroy
    respond_to do |format|
      format.html { redirect_to rental_items_url, notice: 'Rental item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_item
      @rental_item = RentalItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_item_params
      params.require(:rental_item).permit(:description, :price, rental_item_images_attributes: [:id, :rental_item_id, :item_image])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rental_item_images_helper.rb
module RentalItemImagesHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to('Easy', root_path , {:class=>"navbar-brand" })
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"}
            Link
            %span.sr-only (current)
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to('Education Types', "#")
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider{:role => "separator"}
            %li
              %a{:href => "#"} Separated link
            %li.divider{:role => "separator"}
            %li
              %a{:href => "#"} One more separated link
      %form.navbar-form.navbar-left
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}/
        %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            My Account
            %span.caret
          %ul.dropdown-menu
            - if user_signed_in?
              %li
                %a{:href => "#"} Preferences
              %li= link_to('Password', edit_user_registration_path)
              %li= link_to('Google Auth', "#" )
              %li.divider{:role => "separator"}
              %li
                = link_to('Logout', destroy_user_session_path, method: :delete)
            - else
              %li= link_to('Forgot Password', user_password_path )
              %li.divider{:role => "separator"}
              %li
                = link_to('Login', new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title
      Easyrenter - #{yield :title}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navbar'
    .container-fluid
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      - if Rails.env.development?
        %p.alert-info= 'This environment is running in development'
      - if Rails.env.test?
        %p.alert-info= 'This environment is running in test'
      = yield

app/views/rental_item_images/_form.html.haml
= form_for @rental_item_image do |f|
  - if @rental_item_image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rental_item_image.errors.count, "error")} prohibited this rental_item_image from being saved:"
      %ul
        - @rental_item_image.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :rental_item_id
    = f.number_field :rental_item_id
  .field
    = f.label :item_image
    = f.file_field :item_image
  .field
    = f.label :contains_items_not_included
    = f.check_box :contains_items_not_included
  .actions
    = f.submit 'Save'

app/views/rental_item_images/edit.html.haml
%h1 Editing rental_item_image

= render 'form'

= link_to 'Show', @rental_item_image
\|
= link_to 'Back', rental_item_images_path

app/views/rental_item_images/index.html.haml
%h1 Listing rental_item_images

%table
  %thead
    %tr
      %th Rental item
      %th Item image
      %th Contains items not included
      %th
      %th
      %th

  %tbody
    - @rental_item_images.each do |rental_item_image|
      %tr
        %td= rental_item_image.rental_item_id
        %td= rental_item_image.item_image
        %td= rental_item_image.contains_items_not_included
        %td= link_to 'Show', rental_item_image
        %td= link_to 'Edit', edit_rental_item_image_path(rental_item_image)
        %td= link_to 'Destroy', rental_item_image, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Rental item image', new_rental_item_image_path

app/views/rental_item_images/new.html.haml
%h1 New rental_item_image

= render 'form'

= link_to 'Back', rental_item_images_path

app/views/rental_item_images/show.html.haml
%p#notice= notice

%p
  %b Rental item:
  = @rental_item_image.rental_item_id
%p
  %b Item image:
  = @rental_item_image.item_image
%p
  %b Contains items not included:
  = @rental_item_image.contains_items_not_included

= link_to 'Edit', edit_rental_item_image_path(@rental_item_image)
\|
= link_to 'Back', rental_item_images_path

app/views/rental_items/_form.html.haml
= form_for @rental_item do |f|
  - if @rental_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rental_item.errors.count, "error")} prohibited this rental_item from being saved:"
      %ul
        - @rental_item.errors.full_messages.each do |message|
          %li= message
  = f.fields_for :rental_item_images do |p|
    .field
      = p.label :item_image
        - if p.object.item_image?
        = image_tag p.object.item_image.thumb.url
      = p.file_field :item_image, :multiple => true, name: "rental_item_images[item_image][]"
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/rental_items/edit.html.haml
%h1 Editing rental_item

= render 'form'

= link_to 'Show', @rental_item
\|
= link_to 'Back', rental_items_path

app/views/rental_items/index.html.haml
= content_for :title,"Rental Items"
%h1 Listing rental_items

%table
  %thead
    %tr
      %th Description
      %th Price
      %th
      %th
      %th

  %tbody
    - @rental_items.each do |rental_item|
      %tr
        %td= rental_item.description
        %td= rental_item.price
        %td= link_to 'Show', rental_item
        %td= link_to 'Edit', edit_rental_item_path(rental_item)
        %td= link_to 'Destroy', rental_item, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Rental item', new_rental_item_path

app/views/rental_items/new.html.haml
%h1 New rental_item

= render 'form'

= link_to 'Back', rental_items_path

app/views/rental_items/show.html.haml
- @rental_item_images.each do |p|
  %p
    =image_tag p.item_image.thumb.url
    =link_to "Edit Image", edit_rental_item_image_path(p)

%p
  .rental-label
    Description2:
  %i #{@rental_item.description} #{@rental_item.price}

%p
  %b Price:
  = @rental_item.price


= link_to 'Edit', edit_rental_item_path(@rental_item)
\|
#{link_to 'Back', rental_items_path}

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>